"""IELTS Writing curriculum — hardcoded lesson plan + on-demand Claude generation.

Each lesson is defined by a slug, a Russian title, and a focused "what should
this lesson teach" brief. The body is generated by Claude on first read and
cached forever in the DB (one-time cost). The user can regenerate any lesson.
"""
from __future__ import annotations

from dataclasses import dataclass

from app.services.anthropic_client import claude_complete


@dataclass(frozen=True)
class LessonSpec:
    slug: str
    title: str
    summary: str  # one line, shown in the lesson list
    brief: str   # detailed brief fed to Claude


CURRICULUM: tuple[LessonSpec, ...] = (
    LessonSpec(
        slug="task2-overview",
        title="Урок 1. Что такое IELTS Task 2",
        summary="Зачем нужен Task 2, сколько он стоит, по каким критериям его оценивают.",
        brief=(
            "Объясни, что такое IELTS Writing Task 2, сколько он весит относительно Task 1 (две трети), "
            "сколько даётся времени (40 минут), какой минимальный объём (250 слов) и за что снимают баллы. "
            "Кратко перечисли 4 официальных критерия оценки и что в каждом проверяют. "
            "Закончи блоком 'что дальше': подсказка — следующий урок про типы вопросов."
        ),
    ),
    LessonSpec(
        slug="task2-question-types",
        title="Урок 2. Четыре типа вопросов Task 2",
        summary="Opinion · Discuss both views · Problem-solution · Two-part question — как их различать.",
        brief=(
            "Опиши 4 распространённых типа вопросов IELTS Task 2: 1) opinion (To what extent do you agree), "
            "2) discuss both views and give your opinion, 3) problem & solution / causes & effects, "
            "4) two-part question (advantages/disadvantages или комбинированные). "
            "Для каждого: типичные фразы-маркеры, как распознать, что именно нужно написать в ответе, "
            "и одна короткая example question. Это критический урок — если перепутал тип, балл за Task Response упадёт."
        ),
    ),
    LessonSpec(
        slug="task2-structure",
        title="Урок 3. Структура из 4 абзацев",
        summary="Введение / Body 1 / Body 2 / Заключение — каркас отличного эссе.",
        brief=(
            "Покажи стандартную 4-абзацную структуру эссе IELTS Task 2 и сколько слов на каждый абзац (≈40 / 90 / 90 / 30). "
            "Объясни роль каждого: introduction (перефразировать вопрос + thesis), body 1 (одна идея + развитие + пример), "
            "body 2 (вторая идея + развитие + пример), conclusion (краткое подтверждение позиции). "
            "Добавь визуальную схему как ASCII-блок. Подчеркни: высокий балл невозможен без чёткой структуры."
        ),
    ),
    LessonSpec(
        slug="task2-introduction",
        title="Урок 4. Введение и thesis statement",
        summary="Перефразируй вопрос, обозначь свою позицию — 2 предложения.",
        brief=(
            "Научи писать введение Task 2: предложение 1 = перефразировать вопрос (НЕ копировать), "
            "предложение 2 = thesis statement, чётко обозначающий твою позицию или то, что обсудишь. "
            "Покажи 2-3 примера: дана example question и образцовое введение к ней с пояснениями. "
            "Опасные ошибки: копирование, расплывчатый thesis, длинные вступления."
        ),
    ),
    LessonSpec(
        slug="task2-body",
        title="Урок 5. Body paragraph по схеме PEEL",
        summary="Point → Explanation → Example → Link. Как развить одну идею до целого абзаца.",
        brief=(
            "Опиши PEEL framework для тела эссе: Point (главная идея этого абзаца, topic sentence), "
            "Explanation (почему / как / в каком контексте), Example (конкретный, желательно правдоподобный, "
            "не обязательно реальный — можно от себя), Link (вывод/связка с темой эссе). "
            "Покажи 2 полностью развёрнутых body-абзаца на разные темы. Подчеркни: 1 идея = 1 абзац, "
            "не пихать 3 мысли в один блок."
        ),
    ),
    LessonSpec(
        slug="task2-conclusion",
        title="Урок 6. Заключение — кратко и по делу",
        summary="2-3 предложения: повторить позицию, подвести итог. Чего НЕ писать.",
        brief=(
            "Покажи как писать заключение в Task 2: начать с 'In conclusion' / 'To sum up', повторить позицию "
            "другими словами, подвести краткий итог двум аргументам. Не вводить НОВЫХ идей в заключении — "
            "за это снижают балл. Дай 2 примера хорошего заключения и 1 плохого с разбором почему."
        ),
    ),
    LessonSpec(
        slug="task2-cohesion",
        title="Урок 7. Связки и переходы",
        summary="Linking words для критерия Coherence and Cohesion — не более 1-2 на абзац.",
        brief=(
            "Дай каталог linking expressions по функциям: addition (Moreover, Furthermore, In addition), "
            "contrast (However, On the other hand, Whereas), cause (Because of this, As a result), "
            "example (For instance, To illustrate), opinion (In my view, From my perspective), "
            "conclusion (In conclusion, To sum up). Подчеркни ВАЖНОЕ: экзаменаторы снимают балл за overuse — "
            "лучше 1-2 хорошо подобранных связки на абзац, чем 5 шаблонных в каждом предложении."
        ),
    ),
    LessonSpec(
        slug="task2-paraphrasing",
        title="Урок 8. Paraphrasing и лексика B2+",
        summary="Как не повторять слова из вопроса и поднять оценку за Lexical Resource.",
        brief=(
            "Объясни критическую технику paraphrasing для IELTS: замена слов синонимами, изменение части речи, "
            "перестройка структуры предложения. Покажи 3 пары: оригинальный вопрос → перефраз во введении. "
            "Дай мини-словарь high-band синонимов для частых слов: people, important, problem, cause, help, good, bad, "
            "many. Подчеркни: натуральность важнее, чем редкие слова — корявое 'utilise' хуже простого 'use'."
        ),
    ),
)


def get_lesson_spec(slug: str) -> LessonSpec | None:
    return next((l for l in CURRICULUM if l.slug == slug), None)


LESSON_SYSTEM = (
    "You write IELTS Writing lessons for a Russian-speaking learner. "
    "Output is Markdown only — no HTML, no JSON, no commentary outside the lesson. "
    "Lessons are in RUSSIAN; quoted English examples stay in English. "
    "Use clear headings (##), bullet lists, short paragraphs, and concrete example sentences. "
    "Aim for 500-900 words of substantive content — enough to actually teach, not just summarise."
)


async def generate_lesson_body(spec: LessonSpec) -> str:
    user = (
        f"Write the lesson '{spec.title}' for the IELTS Writing curriculum.\n\n"
        f"Brief:\n{spec.brief}\n\n"
        "Structure:\n"
        "1. Короткое введение (1-2 предложения, что узнаем).\n"
        "2. Основная часть с подзаголовками (##), списками, примерами.\n"
        "3. Раздел '## Примеры' с 2-3 английскими примерами и переводом/комментарием на русском.\n"
        "4. Раздел '## Главное' — резюме из 3-5 буллетов.\n"
        "Reply with Markdown only, in Russian."
    )
    reply = await claude_complete(system_prompt=LESSON_SYSTEM, user_message=user)
    return reply.strip().strip("`").strip()
